#!/bin/sh

global bootm.appendroot=1
global bootm.root_dev=mmc2.failsafe.root-FS
global bootm.image=/dev/mmc2.failsafe.fit
global linux.bootargs.dyn.rootwait=rootwait

global linux.bootargs.dyn.bootentries="init=/usr/sbin/platsch fsck.repair=yes usbcore.autosuspend=-1 hw_protection=reboot"
