#!/bin/sh

global bootm.appendroot=1
global bootm.root_dev=mmc2.system1
global bootm.image=/dev/mmc2.system1.fit
global linux.bootargs.dyn.rootwait=rootwait

global linux.bootargs.dyn.bootentries="fsck.repair=yes usbcore.autosuspend=-1 hw_protection=reboot net.ifnames=0"
if [ ${global.hostname} != "imx8mp-skov-revc-bd500" ]; then
    global linux.bootargs.dyn.init_platsch="init=/usr/sbin/platsch"
fi
