#!/bin/sh

global bootm.appendroot=1
global bootm.root_dev=mmc2.system1
global bootm.image=/dev/mmc2.system1.fit
global linux.bootargs.dyn.rootwait=rootwait

global linux.bootargs.dyn.bootentries="init=/usr/sbin/platsch fsck.repair=yes usbcore.autosuspend=-1 hw_protection=reboot net.ifnames=0"
