#!/bin/sh

if [ -z "${global.board.display}" ]; then
  exit
fi

splashscreen=/env/splash${state.display.xres}.png
[ -e ${splashscreen} ] || splashscreen=/env/splash.png

if [ ${state.display.external} -eq 0 ]; then
   fb0.mode_name="${global.board.display}"
   splash -f /dev/fb0 -b 0 ${splashscreen}
   fb0.enable=1
   backlight0.brightness="${state.display.brightness}"
else
   splash -f /dev/fb3 -b 0 ${splashscreen}
   fb3.enable=1
   sleep 1
   BRIGHTNESS=${state.display.brightness}
   if [ ${BRIGHTNESS} -gt 100 ]; then
      BRIGHTNESS=100
   fi
   let CHECKSUM=0x6e^0x51^0x84^0x03^0x10^0x00^${BRIGHTNESS}
   i2c_write -b 0 -a 0x37 -r 0x51 0x84 0x03 0x10 0x00 ${BRIGHTNESS} ${CHECKSUM}
fi
