#!/bin/sh

# Determine display type and register a fixup for display
# timing, so the kernel uses correct display timing

# If PD 2 == HIGH then it is a seiko display, otherwise logic display
# arm9-cpu never used logic l6 so do not try to detect this display

gpio_get_value 98
seiko=$?

if [ $seiko = 1 ]; then
    echo "display: seiko"
    of_display_timings -S /ahb/fb@700000/display0/display-timings/seiko
else
    echo "display: logic l2rt"
    of_display_timings -S /ahb/fb@700000/display0/display-timings/l2rt
fi
